### ISSUE TITLE
Add contributing maintainer

### ISSUE THREAD

**Issue by jaxxstorm** [lbrlabs/pulumi-dynatrace#46]
@williamsbdev happy to add you as a contributor

**Comment by williamsbdev** [comment]
Thank you! I would love that!

**Comment by williamsbdev** [comment]
I have it on my list of things to do, to write up some docs for myself and other people wanting to contribute on how this process works and also adjusting some of the workflows. I've noticed that comments on issues/PRs are triggering workflows to run that are failing.

https://github.com/lbrlabs/pulumi-dynatrace/actions/runs/5072350888
https://github.com/lbrlabs/pulumi-dynatrace/actions/runs/5072523418

I think we've fixed the release with the fixes/changes we've made for .NET (link to the last release we did below but the logs are expired):

https://github.com/lbrlabs/pulumi-dynatrace/actions/runs/3370997492
