### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by williamsbdev** [lbrlabs/pulumi-dynatrace#47]
@jaxxstorm - I've been looking at the release process. From what I can tell, we create a release with this workflow:

https://github.com/lbrlabs/pulumi-dynatrace/actions/workflows/release.yml

We do so with a new tag. Based on the changes that we made, I think we should do a `v0.1.0` release because we renamed a few of the resources, fixing typos, thus introducing a breaking change. Since we're still pre `1.0.0`, a minor version constitutes a breaking change. I'm not sure at what point we would consider this a `1.0.0` release.

Thank you so much for all your help getting to this point!

**Comment by williamsbdev** [comment]
I've just pushed a new tag `v0.1.0` to do a new release of the library.

https://github.com/lbrlabs/pulumi-dynatrace/actions/runs/5079611478

**Comment by jaxxstorm** [comment]
@williamsbdev you also need to create an SDK tag so `git tag sdk/v0.1.0`

**Comment by williamsbdev** [comment]
@jaxxstorm - Thanks for teaching me that! I just did that. It looks like that is the only tag of it's kind though so is that a new requirement?

![image](https://github.com/lbrlabs/pulumi-dynatrace/assets/2402655/95635a95-cc1f-425c-9789-b9fecb05245f)

I also don't see a new action created as a result of that tag. Should there be an action that we take for that tag?

https://github.com/lbrlabs/pulumi-dynatrace/actions

**Comment by jaxxstorm** [comment]
nope, just had forgotten to do it myself for the old tags! it's required for the Go SDK

**Comment by williamsbdev** [comment]
Awesome! I think we can close this one now. :)
